kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: modelserver-nov29-1-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: modelserver-nov29-1-dsp-job
    namespace: modelserver-nov29-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modelserver-nov29-1-dsp-job-role