---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: modelserver-nov29-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelserver-nov29-1 
  name: modelserver-nov29-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi